In [1]:
# numerical python
# intro numpy
import numpy as np

In [2]:
a=np.random.random((10,4))
a

array([[0.81805331, 0.00131026, 0.38445213, 0.36135483],
       [0.02598711, 0.32775142, 0.7944947 , 0.06603137],
       [0.86200367, 0.29047727, 0.28350181, 0.39170528],
       [0.24803027, 0.43448069, 0.50095574, 0.65057252],
       [0.03564857, 0.44462084, 0.51369448, 0.64486957],
       [0.61117216, 0.03806863, 0.80877654, 0.60618041],
       [0.52355301, 0.07983054, 0.56153577, 0.6702878 ],
       [0.81861034, 0.06097769, 0.35633461, 0.88199294],
       [0.99543901, 0.0487111 , 0.63938097, 0.84863154],
       [0.29392857, 0.6100925 , 0.72360484, 0.76734773]])

In [3]:
a.shape

(10, 4)

In [4]:
a.size

40

In [5]:
b=np.random.random((5,3,2))
b

array([[[0.38617133, 0.49583158],
        [0.65556131, 0.22236554],
        [0.81900969, 0.05993894]],

       [[0.34847829, 0.02002571],
        [0.188309  , 0.00148331],
        [0.87704838, 0.12667634]],

       [[0.27349373, 0.25877654],
        [0.69283863, 0.91265228],
        [0.7348062 , 0.35393443]],

       [[0.50510289, 0.69811121],
        [0.94068754, 0.19399909],
        [0.74421527, 0.00998148]],

       [[0.72090576, 0.77391406],
        [0.64214939, 0.85171128],
        [0.92807408, 0.58534788]]])

In [6]:
b.shape

(5, 3, 2)

In [7]:
b.size

30

In [8]:
c=np.random.random((2,3,4,5))
c

array([[[[0.4319117 , 0.54720836, 0.81942646, 0.86468318, 0.64343912],
         [0.78733071, 0.35477817, 0.61622504, 0.92651945, 0.7409542 ],
         [0.50397198, 0.16562731, 0.48498944, 0.45011381, 0.02216435],
         [0.07230035, 0.00708465, 0.33736293, 0.16397362, 0.72320998]],

        [[0.16504132, 0.23208632, 0.8219859 , 0.2395323 , 0.99825774],
         [0.25788903, 0.86204471, 0.13663858, 0.37540695, 0.62114172],
         [0.52636443, 0.0598118 , 0.68594944, 0.10713766, 0.80859816],
         [0.80819313, 0.00539469, 0.22739683, 0.89731546, 0.25666523]],

        [[0.22387244, 0.7830175 , 0.31577628, 0.67193488, 0.95602027],
         [0.66026131, 0.20679455, 0.64735723, 0.63235128, 0.44253174],
         [0.21811835, 0.93651399, 0.0440713 , 0.107314  , 0.87280986],
         [0.12900406, 0.93639479, 0.55405933, 0.60809647, 0.55350206]]],


       [[[0.78610239, 0.23258523, 0.83445931, 0.95502782, 0.21256326],
         [0.37373718, 0.26570886, 0.16744959, 0.64047826, 0.53999186]

In [9]:
a

array([[0.81805331, 0.00131026, 0.38445213, 0.36135483],
       [0.02598711, 0.32775142, 0.7944947 , 0.06603137],
       [0.86200367, 0.29047727, 0.28350181, 0.39170528],
       [0.24803027, 0.43448069, 0.50095574, 0.65057252],
       [0.03564857, 0.44462084, 0.51369448, 0.64486957],
       [0.61117216, 0.03806863, 0.80877654, 0.60618041],
       [0.52355301, 0.07983054, 0.56153577, 0.6702878 ],
       [0.81861034, 0.06097769, 0.35633461, 0.88199294],
       [0.99543901, 0.0487111 , 0.63938097, 0.84863154],
       [0.29392857, 0.6100925 , 0.72360484, 0.76734773]])

In [10]:
a[0]

array([0.81805331, 0.00131026, 0.38445213, 0.36135483])

In [11]:
a[:,0]

array([0.81805331, 0.02598711, 0.86200367, 0.24803027, 0.03564857,
       0.61117216, 0.52355301, 0.81861034, 0.99543901, 0.29392857])

In [12]:
a[4,2]

0.513694481889146

In [13]:
c

array([[[[0.4319117 , 0.54720836, 0.81942646, 0.86468318, 0.64343912],
         [0.78733071, 0.35477817, 0.61622504, 0.92651945, 0.7409542 ],
         [0.50397198, 0.16562731, 0.48498944, 0.45011381, 0.02216435],
         [0.07230035, 0.00708465, 0.33736293, 0.16397362, 0.72320998]],

        [[0.16504132, 0.23208632, 0.8219859 , 0.2395323 , 0.99825774],
         [0.25788903, 0.86204471, 0.13663858, 0.37540695, 0.62114172],
         [0.52636443, 0.0598118 , 0.68594944, 0.10713766, 0.80859816],
         [0.80819313, 0.00539469, 0.22739683, 0.89731546, 0.25666523]],

        [[0.22387244, 0.7830175 , 0.31577628, 0.67193488, 0.95602027],
         [0.66026131, 0.20679455, 0.64735723, 0.63235128, 0.44253174],
         [0.21811835, 0.93651399, 0.0440713 , 0.107314  , 0.87280986],
         [0.12900406, 0.93639479, 0.55405933, 0.60809647, 0.55350206]]],


       [[[0.78610239, 0.23258523, 0.83445931, 0.95502782, 0.21256326],
         [0.37373718, 0.26570886, 0.16744959, 0.64047826, 0.53999186]

In [14]:
c.shape

(2, 3, 4, 5)

In [15]:
c[0]

array([[[0.4319117 , 0.54720836, 0.81942646, 0.86468318, 0.64343912],
        [0.78733071, 0.35477817, 0.61622504, 0.92651945, 0.7409542 ],
        [0.50397198, 0.16562731, 0.48498944, 0.45011381, 0.02216435],
        [0.07230035, 0.00708465, 0.33736293, 0.16397362, 0.72320998]],

       [[0.16504132, 0.23208632, 0.8219859 , 0.2395323 , 0.99825774],
        [0.25788903, 0.86204471, 0.13663858, 0.37540695, 0.62114172],
        [0.52636443, 0.0598118 , 0.68594944, 0.10713766, 0.80859816],
        [0.80819313, 0.00539469, 0.22739683, 0.89731546, 0.25666523]],

       [[0.22387244, 0.7830175 , 0.31577628, 0.67193488, 0.95602027],
        [0.66026131, 0.20679455, 0.64735723, 0.63235128, 0.44253174],
        [0.21811835, 0.93651399, 0.0440713 , 0.107314  , 0.87280986],
        [0.12900406, 0.93639479, 0.55405933, 0.60809647, 0.55350206]]])

In [16]:
c[0,1]

array([[0.16504132, 0.23208632, 0.8219859 , 0.2395323 , 0.99825774],
       [0.25788903, 0.86204471, 0.13663858, 0.37540695, 0.62114172],
       [0.52636443, 0.0598118 , 0.68594944, 0.10713766, 0.80859816],
       [0.80819313, 0.00539469, 0.22739683, 0.89731546, 0.25666523]])

In [17]:
c[0,1,0]

array([0.16504132, 0.23208632, 0.8219859 , 0.2395323 , 0.99825774])

In [18]:
c[0,1,0,1]

0.2320863154198869

In [19]:
lst_lst=[[1,2,3], [4,5,6], [7,8,9]]

In [22]:
d2=[e[0] for e in lst_lst]
d2

[1, 4, 7]

In [20]:
d=np.array(lst_lst)
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
d[:,0]

array([1, 4, 7])

In [24]:
print (a)
np.sum(a)

[[0.81805331 0.00131026 0.38445213 0.36135483]
 [0.02598711 0.32775142 0.7944947  0.06603137]
 [0.86200367 0.29047727 0.28350181 0.39170528]
 [0.24803027 0.43448069 0.50095574 0.65057252]
 [0.03564857 0.44462084 0.51369448 0.64486957]
 [0.61117216 0.03806863 0.80877654 0.60618041]
 [0.52355301 0.07983054 0.56153577 0.6702878 ]
 [0.81861034 0.06097769 0.35633461 0.88199294]
 [0.99543901 0.0487111  0.63938097 0.84863154]
 [0.29392857 0.6100925  0.72360484 0.76734773]]


19.024452498101795

In [25]:
np.sum(a, axis=0)

array([5.232426  , 2.33632093, 5.56673159, 5.88897398])

In [26]:
np.sum(a, axis=1)

array([1.56517052, 1.2142646 , 1.82768803, 1.83403921, 1.63883346,
       2.06419773, 1.83520712, 2.11791557, 2.53216262, 2.39497364])

In [27]:
b

array([[[0.38617133, 0.49583158],
        [0.65556131, 0.22236554],
        [0.81900969, 0.05993894]],

       [[0.34847829, 0.02002571],
        [0.188309  , 0.00148331],
        [0.87704838, 0.12667634]],

       [[0.27349373, 0.25877654],
        [0.69283863, 0.91265228],
        [0.7348062 , 0.35393443]],

       [[0.50510289, 0.69811121],
        [0.94068754, 0.19399909],
        [0.74421527, 0.00998148]],

       [[0.72090576, 0.77391406],
        [0.64214939, 0.85171128],
        [0.92807408, 0.58534788]]])

In [30]:
b[:2].shape

(2, 3, 2)

In [28]:
np.sum(b[:2])

4.20089940933224

In [31]:
np.mean(a)

0.47561131245254484

In [32]:
np.sum(a)/a.size

0.47561131245254484

In [33]:
np.mean(a, axis=0)

array([0.5232426 , 0.23363209, 0.55667316, 0.5888974 ])

In [34]:
np.mean(a, axis=1)

array([0.39129263, 0.30356615, 0.45692201, 0.4585098 , 0.40970836,
       0.51604943, 0.45880178, 0.52947889, 0.63304065, 0.59874341])

In [35]:
x=np.random.random((2,3))
y=np.random.random((2,3))

In [36]:
x

array([[0.42149101, 0.51555467, 0.05789328],
       [0.56992372, 0.44140933, 0.38511909]])

In [37]:
y

array([[0.5556223 , 0.10149137, 0.64052922],
       [0.59902501, 0.99363723, 0.12471804]])

In [38]:
np.add(x,y)

array([[0.9771133 , 0.61704604, 0.6984225 ],
       [1.16894873, 1.43504656, 0.50983713]])

In [41]:
np.subtract(x,y)

array([[-0.13413129,  0.4140633 , -0.58263594],
       [-0.0291013 , -0.55222789,  0.26040105]])

In [42]:
np.multiply(x,y)

array([[0.2341898 , 0.05232435, 0.03708234],
       [0.34139856, 0.43860075, 0.0480313 ]])

In [43]:
np.divide(x,y)

array([[0.75859269, 5.0797882 , 0.09038351],
       [0.9514189 , 0.44423591, 3.08791809]])

In [44]:
np.std(a)

0.2837741629611615

In [45]:
np.std(a, axis=0)

array([0.33659373, 0.20458431, 0.17441772, 0.23730158])

In [46]:
np.std(a, axis=1)

array([0.28946243, 0.30621425, 0.23776185, 0.14454133, 0.22762552,
       0.28780494, 0.22532895, 0.33813291, 0.36031001, 0.18510719])

In [47]:
np.cumsum(a)

array([ 0.81805331,  0.81936357,  1.20381569,  1.56517052,  1.59115763,
        1.91890905,  2.71340375,  2.77943512,  3.64143879,  3.93191606,
        4.21541787,  4.60712314,  4.85515341,  5.2896341 ,  5.79058984,
        6.44116236,  6.47681093,  6.92143177,  7.43512625,  8.07999582,
        8.69116797,  8.7292366 ,  9.53801314, 10.14419355, 10.66774656,
       10.7475771 , 11.30911287, 11.97940067, 12.79801101, 12.85898869,
       13.21532331, 14.09731624, 15.09275525, 15.14146635, 15.78084732,
       16.62947886, 16.92340743, 17.53349992, 18.25710476, 19.0244525 ])

In [48]:
np.cumprod(a)

array([8.18053311e-01, 1.07186033e-03, 4.12078982e-04, 1.48906729e-04,
       3.86965512e-06, 1.26828498e-06, 1.00764569e-06, 6.65362268e-08,
       5.73544719e-08, 1.66601702e-08, 4.72318841e-09, 1.85009782e-09,
       4.58880252e-10, 1.99374607e-10, 9.98778545e-11, 6.49777873e-11,
       2.31636504e-12, 1.02990418e-12, 5.29056094e-13, 3.41172173e-13,
       2.08514933e-13, 7.93787710e-15, 6.41996877e-15, 3.89165929e-15,
       2.03748994e-15, 1.62653918e-16, 9.13359937e-17, 6.12214024e-17,
       5.01164729e-17, 3.05598654e-18, 1.08895378e-18, 9.60449538e-19,
       9.56068935e-19, 4.65711682e-20, 2.97767186e-20, 2.52694626e-20,
       7.42741695e-21, 4.53141137e-21, 3.27895120e-21, 2.51609577e-21])

In [52]:
a.shape

(10, 4)

In [53]:
a.flatten().shape

(40,)

In [55]:
c.shape

(2, 3, 4, 5)

In [54]:
c.flatten().shape

(120,)

In [56]:
a.max()

0.9954390075374463

In [57]:
a.min()

0.0013102573081298363

In [58]:
c.reshape((4,5,2,3))

array([[[[0.4319117 , 0.54720836, 0.81942646],
         [0.86468318, 0.64343912, 0.78733071]],

        [[0.35477817, 0.61622504, 0.92651945],
         [0.7409542 , 0.50397198, 0.16562731]],

        [[0.48498944, 0.45011381, 0.02216435],
         [0.07230035, 0.00708465, 0.33736293]],

        [[0.16397362, 0.72320998, 0.16504132],
         [0.23208632, 0.8219859 , 0.2395323 ]],

        [[0.99825774, 0.25788903, 0.86204471],
         [0.13663858, 0.37540695, 0.62114172]]],


       [[[0.52636443, 0.0598118 , 0.68594944],
         [0.10713766, 0.80859816, 0.80819313]],

        [[0.00539469, 0.22739683, 0.89731546],
         [0.25666523, 0.22387244, 0.7830175 ]],

        [[0.31577628, 0.67193488, 0.95602027],
         [0.66026131, 0.20679455, 0.64735723]],

        [[0.63235128, 0.44253174, 0.21811835],
         [0.93651399, 0.0440713 , 0.107314  ]],

        [[0.87280986, 0.12900406, 0.93639479],
         [0.55405933, 0.60809647, 0.55350206]]],


       [[[0.78610239, 0.23258523, 0.

In [60]:
type(a)

numpy.ndarray

In [61]:
type(a.tolist())

list

In [64]:
(x[0], y[0])

(array([0.42149101, 0.51555467, 0.05789328]),
 array([0.5556223 , 0.10149137, 0.64052922]))

In [63]:
np.dot(x[0], y[0])

0.323596489499722

In [66]:
np.matmul(x,y.T)

array([[0.32359649, 0.77197831],
       [0.60814159, 0.8280306 ]])

In [70]:
x

array([[0.42149101, 0.51555467, 0.05789328],
       [0.56992372, 0.44140933, 0.38511909]])

In [71]:
x.T

array([[0.42149101, 0.56992372],
       [0.51555467, 0.44140933],
       [0.05789328, 0.38511909]])

In [72]:
x.transpose()

array([[0.42149101, 0.56992372],
       [0.51555467, 0.44140933],
       [0.05789328, 0.38511909]])

In [73]:
c.shape

(2, 3, 4, 5)

In [74]:
c.T.shape

(5, 4, 3, 2)

In [75]:
np.var(a)

0.08052777556430782

In [81]:
z=np.random.random((3,3,3))

In [82]:
np.linalg.det(z)

array([ 0.30865043,  0.08375861, -0.28404425])

In [83]:
# https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.ndarray.html

In [84]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [86]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [89]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])